# Data Preprocessing Tools

## Importing the libraries

In [ ]:
#import libraries by matplot, pandas, and numpy
#sklearn has all Machine learning libraries and packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [23]:
#create a new variable for my data set
#read.csv function is inside of pandas library so we have to call pandas first 
#and then call read.csv
dataset= pd.read_csv("Data.csv")
#dependent variable are usually stored in the last column
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [25]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [26]:
#There are several ways to tackle this issue
#1. If we have a large data set and %1 of them is missing we remove those missed data
#2. Replace the missing value by the average of that feature
#we use sklearn to handle missing salary

In [30]:
#imputer is an object from SimpleImputer class and sklearn is a library
#fit, transform are also a method 
#we need to find all numerical columns to replace any missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy= 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [31]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
#Suppose in a large data set we have only 3 categorical data
#so we group them in 3 columns and assign a binary id to them like: 001, 010, ...

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
#adding np.array to make sure we convert it to array representation

In [33]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Independent Variable

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder ()
y= le.fit_transform(y)

In [35]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

In [ ]:
#which one is correct? feature scaling after splitting dataset or 
#after splitting? Correct answer: AFTER splitting the dataset
#it prevents information leakage for test set

In [36]:
from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test are four variable that will be return by 
#train_test_split class
#test_size =0.2 means %20 of dataset is going for test set and %80 is for training set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)


In [37]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [38]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [39]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [40]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
#Two approaches for feature scaling:
#1. standardisation: (x- mean(x))/ standard deviation (x)--> good for all kind of data(recommended)
#2. Normalization: (x-min(x))/ (max(x)- min(x))--> good for normal distribution

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#do we have to apply standardisation for dummy nodes as well? NO
#apply standardisation for training set
#we consider new X and y so the indicies are different for age and salary from the original dataset
X_train [:, 3:] = sc.fit_transform(X_train [:, 3:])
#X_train values are between [-2,+2]
X_test [:, 3:] = sc.transform(X_test [:, 3:])

In [42]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [43]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
