# Data Preprocessing Tools

## Importing the libraries

In [21]:
#import libraries by matplotlib, pandas, and numpy
#sklearn has all Machine learning libraries and packages

In [22]:
import numpy as np #np is a shortcut for numpy
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [23]:
#create a new variable for my data set
#read_csv function is inside of pandas library so we have to call pandas first
#and then call read_csv

In [24]:
dataset = pd.read_csv('Data.csv')
#to get x (matrix of features), get all the first ith columns except the last one
#iloc is a function to locate indices
#featured columns (independent) are those that we use them to guess some properties
X = dataset.iloc[:, :-1].values  #-1 is the last column
#we only want to get the index of last column
#dependent variable are usually stored in the last column
y = dataset.iloc[:, -1].values

In [25]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [26]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [27]:
#one naive apporach would be deleting missing data
#but when we have too much missing data that is not a good approach
#the second approach will be replacing the missing data with average salary

In [28]:
#imputer is an object from SimpleImputer class and sklearn is a library
#fit, transform are also a method
#we need to find all numerical columns to replace any missing values

In [29]:
#from library import class SimpleImputer
from sklearn.impute import SimpleImputer
#instance of this class is imputer
#replace missing value with mean
imputer = SimpleImputer(missing_values= np.nan, strategy = 'mean')
#select all numerical columns (not categorical cols) here columns 1 and 2
#columns indices start from 0
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [30]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [31]:
#Suppose in a large data set we have only 3 categorical data like (Spain, Germany, Italy)
#so we group them in 3 columns and assign a binary id to them like: 001, 010, ...

In [32]:
# we can change categorical data to some numerical data like Germany = 0, France = 1, Spain = 2
# we also can convert these categorical data to a binary vector
# change No to 0 and Yes to 1

### Encoding the Independent Variable

In [33]:
#object from ColumnTransformer class
#encode the first column (categorical col which is also independent)
#instead of having one column since we vectorized the categorical column
#we have three columns
#first column for France, second for Germany, and third for Spain

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#ct is an object of ColumnTransformer class
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
#the first column [0] is our categorical column that we want to encode it
X = np.array(ct.fit_transform(X)) # pass ct.fit_transform(X) to numpy array to force it as an array

In [35]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [36]:
#this time we encode the dependent variable (last column)
#the last column is Yes/No and it is very easy and it is just a label

In [37]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
y = le.fit_transform(y) # we don't need to convert it to an array

In [38]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into the Training set and Test set

In [ ]:
#which one is correct? feature scaling after splitting dataset or
#before splitting? Correct answer: AFTER splitting the dataset
#it prevents information leakage for test set

In [ ]:
# we have to apply feature scaling "after" splitting the dataset
# into the training set and test set, ow. we face the information leakage
# feature scaling shouldn't be applied on test set

In [39]:
from sklearn.model_selection import train_test_split
#80% for train set and 20% for test set
# random_state is a seed
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1 )

In [40]:
print(X_train)
#we have only 8 rows since overall we have 10 cases and 20% is for test

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [41]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [42]:
print(y_train) # corresponds to the first 8 rows (customers)

[0 1 0 0 1 1 0 1]


In [43]:
print(y_test)

[0 1]


# Feature Scaling

In [44]:
# we use standardisation and normalization

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# do we have to apply standardisation (feature scaling) to dummy node (the encoded categorical nodes)? no
# so we only apply standardisation on columns 4 and 5 (3 and 4), we don't have the last column in X_train
X_train [:, 3:] = sc.fit_transform(X_train [:, 3:]) # to get the mean and standard deviation
#X_train values are between [-2,+2] here (overall [-3,+3])
X_test [:, 3:] = sc.transform(X_test [:, 3:])
# we just get the result for test so don't apply fit_transform


In [47]:
print(X_train)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [48]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484425 0.20564033932253029]]
